version: "3.6"

services:
  # Application Node
  crud:
    container_name: crud
    build: ./
    command: npm start
    working_dir: /user/src/crud
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
    links:
      - mongo
    ports:
      - "8080:5000"
    # volumes:
    #   - ./:/user/src/crud

  # Database
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
